#!/usr/bin/python
# Author: Corey Osman
# Date: 2-13-2009
# Purpose: tests the  xmlrpc web interface for jumpstart server


import xmlrpclib



hostname = '172.16.1.53'


# this uri may change when I get a static IP from john
uri = 'http://%s:9000' % (hostname)
remote = xmlrpclib.Server(uri)
print remote.listusers()
print remote.listsystems()
